CREATE DATABASE dbNEW_PHARMA

USE dbNEW_PHARMA

CREATE TABLE tbFornecedor(
ID TINYINT IDENTITY(1,1) NOT NULL,
Nome VARCHAR(50) NOT NULL,
NIF VARCHAR(25) NOT NULL UNIQUE,
Endereco VARCHAR(50) NOT NULL,
Telefone VARCHAR(20) NOT NULL UNIQUE,
E_mail VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
);

SELECT * FROM tbFornecedor

CREATE TABLE tbCategoria(
ID TINYINT IDENTITY(1,1) NOT NULL,
Nome VARCHAR(50) NOT NULL UNIQUE,
PRIMARY KEY(ID),
);

SELECT * FROM tbCategoria

CREATE TABLE tbProduto(
ID INT IDENTITY(1,1) NOT NULL,
Nome VARCHAR(50) NOT NULL,
FornecedorID TINYINT,
CategoriaID TINYINT,
Descricao VARCHAR(100),
Quant_Estoque TINYINT,
Preco DECIMAL NOT NULL,
FOREIGN KEY(FornecedorID) REFERENCES tbFornecedor(ID),
FOREIGN KEY(CategoriaID) REFERENCES tbCategoria(ID),
PRIMARY KEY(ID)
);

SELECT * FROM tbProduto

CREATE TABLE tbFuncionario(
ID TINYINT IDENTITY(1,1) NOT NULL,
Nome VARCHAR(50) NOT NULL,
BI VARCHAR(15) NOT NULL UNIQUE,
Email VARCHAR(30) NOT NULL,
Endereco VARCHAR(50) NOT NULL,
Telefone VARCHAR(20) NOT NULL,
PRIMARY KEY(ID)
);

SELECT * FROM tbFuncionario

CREATE TABLE tbCliente(
ID INT IDENTITY(1,1) NOT NULL,
Nome VARCHAR(50) NOT NULL UNIQUE,
N_BI VARCHAR(20) NOT NULL UNIQUE,
Endereco VARCHAR(50) NOT NULL,
Telefone VARCHAR(20) NOT NULL UNIQUE,
PRIMARY KEY(ID)
);

SELECT * FROM tbCliente

CREATE TABLE tbVenda(
ID INT IDENTITY(1,1) NOT NULL,
DATA DATETIME,
ClienteID INT,
ProdutoID INT,
Quantidade INT NOT NULL,
Valor_Total DECIMAL NOT NULL,
FuncionarioID TINYINT,
FOREIGN KEY (ClienteID) REFERENCES tbCliente(ID),
FOREIGN KEY (ProdutoID) REFERENCES tbProduto(ID),
FOREIGN KEY (FuncionarioID) REFERENCES tbFuncionario(ID),
PRIMARY KEY(ID)
);

SELECT * FROM tbVenda

CREATE TABLE tbItem_Venda(
ID INT IDENTITY(1,1) NOT NULL,
VendaID INT,
ProdutoID INT,
Quantidade INT NOT NULL,
Preco_Unitario DECIMAL NOT NULL,
FOREIGN KEY(VendaID) REFERENCES tbVenda(ID),
FOREIGN KEY(ProdutoID) REFERENCES tbProduto(ID),
PRIMARY KEY(ID)
);

EXEC sp_help 'tbItem_Venda';

SELECT * FROM tbItem_Venda

