CREATE DATABASE dbNEW_PHARMA

USE dbNEW_PHARMA

CREATE TABLE tbFornecedor(
ID TINYINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL,
NIF VARCHAR(25) NOT NULL UNIQUE,
Endereco VARCHAR(50) NOT NULL,
Telefone VARCHAR(20) NOT NULL UNIQUE,
E_mail VARCHAR(50) NOT NULL,
);

SELECT * FROM tbFornecedor

CREATE TABLE tbCategoria(
ID TINYINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL UNIQUE,
);

SELECT * FROM tbCategoria

CREATE TABLE tbProduto(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL,
Descricao nvarchar(max),
Quant_Estoque TINYINT,
Preco DECIMAL NOT NULL,
CategoriaID TINYINT,
FornecedorID TINYINT,
FOREIGN KEY(FornecedorID) REFERENCES tbFornecedor(ID),
FOREIGN KEY(CategoriaID) REFERENCES tbCategoria(ID),
);

SELECT * FROM tbProduto

CREATE TABLE tbFuncionario(
ID TINYINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL,
N_BI VARCHAR(15) NOT NULL UNIQUE,
Email VARCHAR(30) NOT NULL,
Endereco VARCHAR(50) NOT NULL,
Telefone VARCHAR(20) NOT NULL,
);

SELECT * FROM tbFuncionario

CREATE TABLE tbCliente(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Nome VARCHAR(50) NOT NULL UNIQUE,
N_BI VARCHAR(20) NOT NULL UNIQUE,
Endereco VARCHAR(50) NOT NULL,
Telefone VARCHAR(20) NOT NULL UNIQUE,
);

SELECT * FROM tbCliente

CREATE TABLE tbVenda(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
DATA DATETIME,
ClienteID INT,
ProdutoID INT,
Quantidade INT NOT NULL,
Valor_Total DECIMAL NOT NULL,
FuncionarioID TINYINT,
FOREIGN KEY (ClienteID) REFERENCES tbCliente(ID),
FOREIGN KEY (ProdutoID) REFERENCES tbProduto(ID),
FOREIGN KEY (FuncionarioID) REFERENCES tbFuncionario(ID),
);

SELECT * FROM tbVenda

CREATE TABLE tbItem_Venda(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
VendaID INT,
ProdutoID INT,
Quantidade INT NOT NULL,
Preco_Unitario DECIMAL NOT NULL,
FOREIGN KEY(VendaID) REFERENCES tbVenda(ID),
FOREIGN KEY(ProdutoID) REFERENCES tbProduto(ID),
);

EXEC sp_help 'tbItem_Venda';

SELECT * FROM tbItem_Venda

INSERT INTO tbCategoria VALUES('ANALGESICOS');  

SELECT * FROM tbCategoria

DELETE FROM tbCategoria

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Categoria';
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Categoria';

SELECT DB_NAME();

